<?php
    var_dump($_GET);
    $prenom = $_GET['prenom'];
    $nom = $_GET['nom'];
    $email = $_GET['email'];
    $tel = $_GET['telephone'];
    $github = $_GET['github'];
    $linkedIn = $_Get['linkedin'];
    $bio = $_GET['biographie'];
    $lang =$_GET['lang'];
    
   
?>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            CV
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="style.css" />
    </head>
    <body id="cv" class="blue">
        <header>
            <h1><span><?php echo $_GET['nom'] ?></span><?php echo $_GET['prenom'] ?></h1>
            <h2>Intitulé du poste</h2>
        </header>
        <main>
            <section id="left">
                <h3>Informations</h3>
                <section>
                    <h4>
                        Contact
                    </h4>
                    <dl>
                        <dt>
                            Email
                        </dt>
                        <dd>
                            <?php echo $_GET['email'] ?>
                        </dd>
                        <dt>
                            Téléphone
                        </dt>
                        <dd>
                           <?php echo $_GET['telephone'] ?>
                        </dd>
                        <dt>
                            LinkedIn
                        </dt>
                        <dd>
                            <a href="">https://linkedin.com/example</a>
                        </dd>
                        <dt>
                            GitHub
                        </dt>
                        <dd>
                            <a href="">https://github.com/example</a>
                        </dd>
                    </dl>
                </section>
                <section>
                    <h4>Biographie</h4>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Curabitur sed commodo leo. Duis a gravida libero.
                        Aenean rutrum libero ipsum, a ullamcorper nibh mollis et.
                        Phasellus feugiat cursus risus, eget pharetra tellus interdum in.
                        Nam consectetur urna ipsum, nec porta arcu pharetra ac.
                        Curabitur sed imperdiet massa. Donec nec erat eros.
                        Aenean sed magna eleifend lectus dictum elementum ac at est.
                        In tempor lacus ligula, sed lobortis arcu aliquam eget.
                    </p>
                </section>
                <section>
                    <h4>Loisirs</h4>
                    <ul>
                        <li>
                            Jeux de stratégie
                        </li>
                        <li>
                            Violon
                        </li>
                        <li>
                            Roller Derby
                        </li>
                        <li>
                            Voile
                        </li>
                    </ul>
                </section>
            </section>
            <section id="right">
                <h3>Compétences</h3>
                <section>
                    <h4>Langages des programmation</h4>
                    <ul>
                        <li>HTML</li>
                        <li>CSS</li>
                        <li>JavaScript</li>
                        <li>PHP</li>
                        <li>SQL</li>
                    </ul>
                </section>
                <section>
                    <h4>Frameworks & Librairies</h4>
                    <ul>
                        <li>Sass</li>
                        <li>Bootstrap</li>
                        <li>Symfony</li>
                        <li>Laravel</li>
                    </ul>
                </section>
                <section>
                    <h4>Logiciels</h4>
                    <ul>
                        <li>Photoshop</li>
                        <li>Illustrator</li>
                        <li>XD</li>
                        <li>Figma</li>
                    </ul>
                </section>
                <section>
                    <h4>Langues</h4>
                    <ul>
                    <?php  foreach ($_GET['lang'] as $item) { ?>
                    
                    <li><?php '$item' ?> </li>
                
                    </ul>
                </section>
            </section>
        </main>
    </body>
</html>